# cf https://github.com/tatsu-lab/stanford_alpaca#fine-tuning
model_name_or_path: meta-llama/Llama-2-7b-hf
trainer:
  mp: p=f32,c=bfloat16
  wandb:
    project: "levanter-alpaca"
    tags: ["llama2"]
  num_train_steps: 1218  # 128 * 1218 = 155904, which is almost but not quite 3 epochs, which is what alpaca did
  train_batch_size: 128

  # if using model parallelism, this is useful:
  tensor_parallel_axes: ["mlp", "heads"]
optimizer:
  learning_rate: 2e-5
  weight_decay: 0.0
