data:
  configs:
    wikitext:
      id: dlwh/wikitext_103_detokenized
    w2:
      id: dlwh/wikitext_103_detokenized
  train_weights:
    wikitext: 0.5
    w2: 0.5
model:
  type: gpt2
  hidden_dim: 32
  num_heads: 4
  num_layers: 2
trainer:
  mp: f32
  num_train_steps: 100

  checkpointer:
    keep:
      - every: 50
    save_interval: 5m

  train_batch_size: 32

  tensor_parallel_axes: ["mlp", "heads"]
  fsdp_axis: "embed"
  batch_axis: "batch"
