data:
  train_urls:
    - "gs://data-values/fineweb_edu_10bt_shuffled/fineweb_edu_10bt.chunk.00.jsonl"
  validation_urls:
    - "gs://data-values/fineweb_edu_10bt_shuffled/fineweb_edu_10bt.val.jsonl"
  cache_dir: "gs://data-values/fineweb_edu_10bt_shuffled/cache"
  #id: dlwh/wikitext_103_detokenized
  #id: Tristan/RedPajama-Data-V2-sample-100B-filtered-shuffled-tokenized-with-token-counts
model:
  type: llama
  hidden_dim: 768
  intermediate_dim: 3072
  num_heads: 12
  num_kv_heads: 12
  num_layers: 12
  seq_len: 128
  gradient_checkpointing: false
  layer_norm_epsilon: 1e-2
  qk_norm: true
trainer:
  mp: p=f32,c=f32
  model_axis_size: 1
  per_device_parallelism: 32
  per_device_eval_parallelism: 32

  #profiler: true
  #profiler_start_step: 5
  #profiler_num_steps: 10
  #backward_profiler: true
  #backward_profiler_start_step: 15
  #backward_profiler_num_steps: 10
  #log_dir: "jax_profile_traces"

  train_batch_size: 8192
  num_train_steps: 20
  max_eval_batches: 1

  ray:
    auto_start_cluster: false

  tracker:
    - type: wandb
      project: "levanter"
      name: "tpu_test_s128_b8192"

  checkpointer:
    keep:
      - every: 1
    save_interval: 5m
    base_path: "gs://data-values/checkpoints/test/"


  load_debug_weights: false

  #id: llama_1k_yolo
  #load_checkpoint_path: "/scr-ssd/sampark/levanter/checkpoints/gpt2_1k_yolo_ln_before"

  metagrad_checkpoint_frequency: 20

out_dir: out_dir_test
optimizer:
  lr_schedule: linear
  learning_rate: 1E-4
  weight_decay: 0.1
  warmup: 0.1