# Example config to evaluate a llama3 checkpoint with eval_sliding_lm.py
# Evaluates the validation split of the tulu-3 SFT mixture.

checkpoint_path: "gs://path/to/checkpoint"  # set to your checkpoint

# Dataset processed with SingleTurnChatProcessor
data:
  id: allenai/tulu-3-sft-mixture
  format:
    type: "chat"
  tokenizer: stanford-crfm/marin-tokenizer
  cache_dir: "gs://marin-us-central2/tokenized/marin-tokenizer/tulu-3-sft-mixture"
  shuffle: false

model:  # 8B llama3 model
  type: llama
  seq_len: 4096
  hidden_dim: 4096
  intermediate_dim: 14336
  num_layers: 32
  num_heads: 32
  num_kv_heads: 8
  flash_attention_block_size: 512
  use_bias: false
  use_layer_norm_weight: true
  initializer_range: 0.02
  rope:
    type: "llama3"

trainer:
  seed: 0
  tracker:
    type: wandb
    project: "marin"
    tags: ["llama3", "eval"]
  mp: p=f32,c=bfloat16
  per_device_eval_parallelism: -1
  tensor_parallel_axes: ["mlp", "heads"]
  fsdp_axis: "embed"
  batch_axis: "batch"

