#data:
#  id: dlwh/wikitext_103_detokenized

disable_jit: true

model:
  type: gpt2
  hidden_dim: 32
  num_heads: 4
  num_layers: 2
trainer:
  mp: f32
  num_train_steps: 100

  checkpointer:
    keep:
      - every: 50
    save_interval: 5m

  per_device_parallelism: -1
  train_batch_size: 32

  tensor_parallel_axes: ["mlp", "heads"]
  fsdp_axis: "embed"
  batch_axis: "batch"

data:
  id: dlwh/wikitext_103_detokenized
  cache_dir: /workspace/marin_cache
  tokenizer: gpt2
  format:
    type: ul2r
    text_key: text
    task_configs:
      r:
        type: rx
        mask_prob: 0.15
        mean_span_length: 3.0
        random_roll: true
        task_token_id: 50155
      x1:
        type: rx
        mask_prob: 0.15
        mean_span_length: 32.0
        random_roll: true
        task_token_id: 50155
      x2:
        type: rx
        mask_prob: 0.5
        mean_span_length: 3.0
        random_roll: true
        task_token_id: 50155
      s:
        type: s
        task_token_id: 50156
    task_probs:
      r: 0.5
      x1: 0.125
      x2: 0.125
      s: 0.25
    rng_seed: 42
    # GPT2 vocab_size = 50257
    # eos/bos = 50256
    sentinel_token_id_start: 50157
    sentinel_token_id_count: 99
