data:
  train_urls:
      - "gs://pubmed-mosaic/openwebtext-sharded/openwebtext_train.{1..128}-of-128.jsonl.gz"
  validation_urls:
      - "gs://pubmed-mosaic/openwebtext-sharded/openwebtext.{1..8}-of-8.jsonl.gz"
  cache_dir: "gs://pubmed-mosaic/tokenized/openwebtext/"
model:
  hidden_dim: 4096
  num_heads: 32
  num_layers: 32
  seq_len: 2048
  gradient_checkpointing: true
  scale_attn_by_inverse_layer_idx: true
  attn_pdrop: 0.0
  resid_pdrop: 0.0
trainer:
  mp: p=f32,c=bfloat16
  learning_rate: 1.2E-4
  weight_decay: 0.1

  model_axis_size: 4
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1

  train_batch_size: 2048
  num_train_steps: 100000
  num_eval_steps: 500
  num_save_steps: 4000

  axis_resources:
    batch: "data"
    vocab: "model"
    mlp: "model"
    heads: "model"
  # ZERO-3
  parameter_axis_resources:
    embed: "data"
