data_mixture:
  configs:
    owt: !include data/openwebtext_source.yaml
    pile: !include data/pile_source_old.yaml
  weights:
    pile: 0.6
    redpajama: 0.4
model:
  type: gpt2
  hidden_dim: 32
  num_heads: 4
  num_layers: 2
trainer:
  num_train_steps: 100
  train_batch_size: 32
