data:
  configs:
    owt:
      train_urls:
        - "gs://pubmed-mosaic/openwebtext-sharded/openwebtext_train.{1..128}-of-128.jsonl.gz"
      validation_urls:
        - "gs://pubmed-mosaic/openwebtext-sharded/openwebtext_val.{1..8}-of-8.jsonl.gz"
    wikitext:
      id: dlwh/wikitext_103_detokenized
  train_weights:
    owt: 0.6
    wikitext: 0.4
  tokenizer: gpt2
  cache_dir: "gs://levanter-data/tokenized/data_mix"
model:
  type: gpt2
  hidden_dim: 32
  num_heads: 4
  num_layers: 2
trainer:
  num_train_steps: 100
  train_batch_size: 32
