data:
  train_urls:
      - "gs://pubmed-mosaic/openwebtext-sharded/openwebtext_train.{1..128}-of-128.jsonl.gz"
  validation_urls:
      - "gs://pubmed-mosaic/openwebtext-sharded/openwebtext.{1..8}-of-8.jsonl.gz"
  cache_dir: "gs://pubmed-mosaic/tokenized/openwebtext/"
model:
  hidden_dim: 4096
  num_heads: 32
  num_layers: 32
  seq_len: 1024
  gradient_checkpointing: true
  scale_attn_by_inverse_layer_idx: true
trainer:
  mp: p=f32,c=bfloat16
  learning_rate: 1.2E-4
  weight_decay: 0.1
  model_axis_size: 4
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8
  train_batch_size: 1024

  axis_mapping:
    batch: "data"
    # ZERO-3
    # "embed": ResourceAxis.DATA,
    vocab: "model"
    mlp: "model"
    heads: "model"
