data: !include data/fineweb_llama_md.yaml
model:  # 1B class model
  type: llama
  seq_len: 2048
  hidden_dim: 2048
  intermediate_dim: 8192
  num_layers: 16
  num_heads: 16
  num_kv_heads: 16
  use_flash_attention: True
  flash_attention_block_size: 1024
trainer:
  tracker:
    type: wandb
    project: "marin"
    tags: ["llama", "fineweb", "markdown"]

  mp: p=f32,c=bfloat16
  train_batch_size: 2048  # 2048 * 2048 = 4,194,304
  num_train_steps: 71526  # 300,000,000,000 / 4,194,304 = 71,526
  steps_per_eval: 1000
  tensor_parallel_axes: ["mlp", "heads"]
  fsdp_axis: "embed"
  batch_axis: "batch"
optimizer:
  learning_rate: 4E-4
  weight_decay: 0.1
  min_lr_ratio: 0.1
  warmup: 5000
