data: !include data/dclm_gpt_neo.yaml
model:  # 22B class model
  type: llama
  seq_len: 4096
  hidden_dim: 6144
  intermediate_dim: 16384
  num_layers: 56
  num_heads: 48
  num_kv_heads: 16
  use_flash_attention: True
trainer:
  tracker:
    type: wandb
    entity: "stanford-mercury"
    project: "marin"
    tags: ["dclm", "22B", "llama"]

  mp: p=f32,c=bfloat16
  train_batch_size: 512
  num_train_steps: 100000
  steps_per_eval: 1000
  tensor_parallel_axes: ["mlp", "heads"]
  fsdp_axis: "embed"
  batch_axis: "batch"
optimizer:
  learning_rate: 1e-4
  weight_decay: 0.1
  min_lr_ratio: 0.1
  beta1: 0.9
  beta2: 0.95
  warmup: 5000

z_loss_weight: 5e-6
