data: !include data/dclm_gpt_neo.yaml
model:  # 7B class model
  type: llama
  seq_len: 2048
  hidden_dim: 4096
  intermediate_dim: 11008
  num_layers: 32
  num_heads: 32
  num_kv_heads: 32
  use_flash_attention: True
  flash_attention_block_size: 1024
trainer:
  tracker:
    type: wandb
    project: "marin"
    tags: ["dclm", "7B", "llama"]

  mp: p=f32,c=bfloat16
  train_batch_size: 2048
  num_train_steps: 750000  # 3,000,000,000,000 / 4,000,000 = 750,000
  steps_per_eval: 1000
  tensor_parallel_axes: ["mlp", "heads"]
  fsdp_axis: "embed"
  batch_axis: "batch"
optimizer:
  learning_rate: 4E-4
  weight_decay: 0.1
  min_lr_ratio: 0.1
  warmup: 0.01
