data: !include data/openwebtext_source.yaml
model:
  type: llama
  seq_len: 4096
  hidden_dim: 768
  intermediate_dim: 3072
  num_layers: 12
  num_heads: 12
  num_kv_heads: 12
trainer:
  tracker:
    project: "levanter"
    tags: ["pile", "llama"]
  mp: p=f32,c=bfloat16
  model_axis_size: 1
  checkpointer:
    keep:
      - every: 1000
    save_interval: 30m
    

  train_batch_size: 1024
  per_device_parallelism: 32  # set for v3 TPU
  per_device_eval_parallelism: 32 # set a larger batch size for eval
  num_train_steps: 50001
optimizer:
  learning_rate: 1E-3
  weight_decay: 0.1
  warmup: 1000
  cooldown: 0.1
  lr_schedule: constant
  min_lr_ratio: 0.0 
  max_grad_norm: 1.0
  type: kron
