data:
  train_urls:
    - "gs://pubmed-mosaic/openwebtext-sharded/openwebtext_train.{1..128}-of-128.jsonl.gz"
  validation_urls:
    - "gs://pubmed-mosaic/openwebtext-sharded/openwebtext_val.{1..8}-of-8.jsonl.gz"
  cache_dir: "gs://levanter-data/tokenized/openwebtext_llama/"
  tokenizer: "meta-llama/Llama-2-70b-hf"
model:
  type: llama
initialize_from_hf: "meta-llama/Llama-2-7b-hf"
use_hf_model_config: true
trainer:
  wandb:
    project: "levanter"
    tags: ["openwebtext", "llama"]

  mp: p=f32,c=bfloat16

  train_batch_size: 1024
  num_train_steps: 1000
  steps_per_eval: 50
optimizer:
  learning_rate: 1.2E-5  # set low for fine-tuning
  weight_decay: 0.1
  min_lr_ratio: 0.1
