data: !include data/wikitext_source.yaml
model:
  type: llama
  hidden_dim: 32
  num_heads: 4
  num_layers: 2
trainer:
  mp: p=f32
  train_batch_size: 32
  num_train_steps: 100
  steps_per_eval: 50
  per_device_eval_parallelism: 1
  per_device_parallelism: 1
  tensor_parallel_axes: ["mlp", "heads"]
  fsdp_axis: "embed"
  batch_axis: "batch"
