data:
  train_urls:
    - "gs://marin-us-central2/documents/instruct/tulu_v2_mix/text/tulu-v2-sft-mixture-000.jsonl.gz"
    - "gs://marin-us-central2/documents/instruct/tulu_v2_mix/text/tulu-v2-sft-mixture-001.jsonl.gz"
    - "gs://marin-us-central2/documents/instruct/tulu_v2_mix/text/tulu-v2-sft-mixture-002.jsonl.gz"
  cache_dir: "gs://marin-data/tokenized/tuluv2-train/"
  tokenizer: "allenai/OLMo-1B"
model:  # 7B class model
  type: llama
  seq_len: 4096
  hidden_dim: 4096
  intermediate_dim: 11008
  num_layers: 32
  num_heads: 32
  num_kv_heads: 32
  use_flash_attention: True
#  flash_attention_block_size: 1024

  use_bias: false
  use_layer_norm_weight: false
trainer:
  tracker:
    type: wandb
    project: "marin"
    tags: ["dolma", "olmo", "llama"]

  mp: p=f32,c=bfloat16
  train_batch_size: 64
  num_train_steps: 750000  # 3,000,000,000,000 / 4,000,000 = 750,000
  steps_per_eval: 10
  tensor_parallel_axes: ["mlp", "heads"]
  fsdp_axis: "embed"
  batch_axis: "batch"
  per_device_eval_parallelism: 4

   checkpointer:
      keep:
        - every: 100
          until: 10000
    
optimizer:
  learning_rate: 2E-5
  weight_decay: 0.0
  min_lr_ratio: 0.1
  warmup: 0.03
  beta1: 0.9
  beta2: 0.95

# OLMO SFT config below
