data:
  cache_dir: "gs://levanter-data/tokenized/pile-old/"
  tokenizer: "EleutherAI/gpt-neox-20b"
  rows_per_chunk: 32768
model:
  # 1B class model
  type: llama
  seq_len: 2048
  hidden_dim: 2048
  intermediate_dim: 4096
  num_layers: 24
  num_heads: 32
  num_kv_heads: 32
  use_flash_attention: True
  flash_attention_block_size: 2048
trainer:
  tracker:
    type: wandb
    project: "markweb"
    tags: ["pile", "llama", "web_comparison"]

  mp: p=f32,c=bfloat16
  train_batch_size: 512
  num_train_steps: 50000
  steps_per_eval: 1000
  per_device_eval_parallelism: 64
  tensor_parallel_axes: ["mlp", "heads"]
  fsdp_axis: "embed"
  batch_axis: "batch"
optimizer:
  learning_rate: 2E-4
  weight_decay: 0.1
  min_lr_ratio: 0.1
