eval_harness:
#  task_spec: ["hellaswag"]
  task_spec:
    - task: commonsense_qa  # 5-way multiple-choice questions based on common-sense, everyday scenarios
      num_fewshot: 1
tokenizer: "gpt2"
model:
  type: gpt2
  hidden_dim: 32
  num_heads: 4
  num_layers: 2
trainer:
  mp: f32
  num_train_steps: 100
  profiler: true

  checkpointer:
    keep:
      - every: 50
    save_interval: 5m

  per_device_parallelism: -1
  train_batch_size: 32

  tensor_parallel_axes: ["mlp", "heads"]
  fsdp_axis: "embed"
  batch_axis: "batch"
