name: Pre-Commit

on: [push, pull_request]

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository)

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
        jax-version: ["0.4.38"]

    steps:
      - uses: actions/checkout@v4
      - name: Install uv and Python
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.20"
          python-version: ${{ matrix.python-version }}
          enable-cache: true
      - name: Install dependencies
        run: |
          uv pip install --system flake8 pytest pre-commit
          uv pip install --system . "jax[cpu]==${{ matrix.jax-version }}" "jaxlib==${{ matrix.jax-version }}"
      - name: "Run Pre-commit"
        run: pre-commit run --all-files --show-diff-on-failure


