name: Run tests

on: [push, pull_request]

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository)

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
        jax-version: ["0.5"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          # install uv
          pip install uv
          uv venv
          uv sync --extra dev
      - name: Test with pytest
        run: |
          PYTHONPATH=tests:src:. .venv/bin/pytest tests -m "not entry and not slow and not ray"
