name: Run tests that use ray

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
        jax-version: ["0.5.2"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          # install uv
          pip install uv
          uv venv
          uv sync
      - name: Run ray tests with pytest
        run: |
          PYTHONPATH=$(pwd)/tests:$(pwd)/src:$(pwd):. uv run pytest tests -m ray
