name: Run tests that use ray

on: [push]

jobs:
  ray_tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
        jax-version: ["0.5.2"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        run: |
          pip install uv
      - name: Test with pytest
        run: |
          PYTHONPATH=tests:src:. uv run --extra dev pytest tests -m "ray"
